/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modulos.AuxiliarFrm;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rptrs
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Instancia los paneles que se utilizarán en el cardlayout del JFrame frmPrinicipal
     */
    AuxiliarFrm aux;
    CardLayout card;
    pnlShell shell;
    
//    pnlConvertirCNV cnv;
//    pnlCarcaza carcaza;
//    pnlParameters param;
/*
  * Declaración de variables que almacenarán la ruta en memoria de los archivos creados
  *  o cargados 
  */
    String rut_cnv,rut_dat,rut_sta,rut_mod,rut_par;
    
    public frmPrincipal() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        card = new CardLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContainer = new javax.swing.JPanel();
        pnlCarcaza1 = new Vista.pnlCarcaza();
        pnlConvertirCNV1 = new Vista.pnlConvertirCNV();
        pnlDataCP1 = new Vista.pnlDataCP();
        pnlParameters1 = new Vista.pnlParameters();
        pnlEstaciones1 = new Vista.pnlEstaciones();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmCNV = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlContainer.setLayout(new java.awt.CardLayout());

        pnlCarcaza1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnlCarcaza1FocusLost(evt);
            }
        });
        pnlContainer.add(pnlCarcaza1, "card2");
        pnlContainer.add(pnlConvertirCNV1, "card3");
        pnlContainer.add(pnlDataCP1, "card5");
        pnlContainer.add(pnlParameters1, "card6");
        pnlContainer.add(pnlEstaciones1, "card7");

        itmCNV.setText("Configuración");

        jMenuItem1.setText("Crear archivo .CNV");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem1);

        jMenuItem2.setText("Crear archivo .STA");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem2);

        jMenuItem3.setText("Crear model inicial");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem3);

        jMenuItem4.setText("Crear retícula corteza");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem4);

        jMenuItem5.setText("Modificar parámetros PARAM");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem5);

        jMenuItem6.setText("Modificar parámetros TOMO (datacp)");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem6);

        jMenuItem7.setText("Ejecutar tomo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        itmCNV.add(jMenuItem7);

        jMenuBar1.add(itmCNV);

        jMenu2.setText("Leer archivos");

        jMenuItem8.setText("Leer archivo CARCAZA");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Convertir archivo RES2");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Ver resultados TOMO");
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Graficar Resultados TOMO");
        jMenu2.add(jMenuItem11);

        jMenuItem12.setText("Grabar Archivos");
        jMenu2.add(jMenuItem12);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        limpiarPanel();
        pintarPanel(getPnlConvertirCNV1());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       limpiarPanel();
        getPnlContainer().add(getPnlDataCP1());
        getPnlContainer().repaint();
        pnlContainer.revalidate();    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        limpiarPanel();
        pintarPanel(getPnlEstaciones1());
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        limpiarPanel();
        pintarPanel(getPnlCarcaza1());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        limpiarPanel();
        pintarPanel(getPnlParameters1());
        if(!getPnlCarcaza1().getRut_mod().equals("")){
            getPnlParameters1().getLblMod().setText(getPnlCarcaza1().getRut_mod());
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        shell = new pnlShell();
        limpiarPanel();
        pintarPanel(shell);
        shell.getTxtComando().setText("g77 -o tomo tomo.f");
        {
        }    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        limpiarPanel();
        pintarPanel(getPnlCarcaza1());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void pnlCarcaza1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlCarcaza1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlCarcaza1FocusLost

    /*
     * limpiarPanel()
     * Borra el layout actual 
     * del panel
     */
    public void limpiarPanel() {
        getPnlContainer().removeAll();
        getPnlContainer().repaint();
        getPnlContainer().revalidate();
    }
    /*
     * pintarPanel()
     * Parametros: Jpanel pnl
     * Agrega el layout pnl al panel
     */

    public void pintarPanel(JPanel pnl) {
        getPnlContainer().add(pnl);
        getPnlContainer().repaint();
        getPnlContainer().revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itmCNV;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private Vista.pnlCarcaza pnlCarcaza1;
    private javax.swing.JPanel pnlContainer;
    private Vista.pnlConvertirCNV pnlConvertirCNV1;
    private Vista.pnlDataCP pnlDataCP1;
    private Vista.pnlEstaciones pnlEstaciones1;
    private Vista.pnlParameters pnlParameters1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the pnlCarcaza1
     */
    public Vista.pnlCarcaza getPnlCarcaza1() {
        return pnlCarcaza1;
    }

    /**
     * @return the pnlContainer
     */
    public javax.swing.JPanel getPnlContainer() {
        return pnlContainer;
    }

    /**
     * @return the pnlConvertirCNV1
     */
    public Vista.pnlConvertirCNV getPnlConvertirCNV1() {
        return pnlConvertirCNV1;
    }

    /**
     * @return the pnlDataCP1
     */
    public Vista.pnlDataCP getPnlDataCP1() {
        return pnlDataCP1;
    }

    /**
     * @return the pnlEstaciones1
     */
    public Vista.pnlEstaciones getPnlEstaciones1() {
        return pnlEstaciones1;
    }

    /**
     * @param pnlEstaciones1 the pnlEstaciones1 to set
     */
    public void setPnlEstaciones1(Vista.pnlEstaciones pnlEstaciones1) {
        this.pnlEstaciones1 = pnlEstaciones1;
    }

    /**
     * @return the pnlParameters1
     */
    public Vista.pnlParameters getPnlParameters1() {
        return pnlParameters1;
    }

    /**
     * @param pnlParameters1 the pnlParameters1 to set
     */
    public void setPnlParameters1(Vista.pnlParameters pnlParameters1) {
        this.pnlParameters1 = pnlParameters1;
    }
}
